AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM Template for Cities module.'

Globals:
  Function:
    Timeout: 30     # seconds
    MemorySize: 512 # MB
    Runtime: provided.al2023
    Architectures:
      - arm64

Parameters:
  ResourceDeletionPolicy:
    Type: String
    Default: 'Delete'
    AllowedValues:
      - Retain
      - Delete
    Description: 'Deletion policy for table/log resources. For Snapshot, you need to create a manual backup before deleting the stack to preserve the data.'

  SpringProfile:
    Type: String
    Default: 'dev'
    AllowedValues:
      - dev
      - qa
      - prod
    Description: 'Spring profile for the functions.'

  LogRetentionInDays:
    Type: Number
    Default: 7
    AllowedValues:
      - 7
      - 14
      - 30
    Description: 'Log retention in days for the functions.'

  AnomalyDetectorEvaluationFrequency:
    Type: String
    Default: 'ONE_HOUR'
    AllowedValues:
      - FIVE_MIN
      - TEN_MIN
      - FIFTEEN_MIN
      - THIRTY_MIN
      - ONE_HOUR
    Description: 'Anomaly detector evaluation frequency in minutes.'

Resources:
  CitiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'Cities'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: S
      KeySchema:
        - AttributeName: 'id'
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 2
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: !Ref ResourceDeletionPolicy

  CityDataFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AWS::StackName}/CityDataFunction"
      RetentionInDays: !Ref LogRetentionInDays
    UpdateReplacePolicy: Retain
    DeletionPolicy: !Ref ResourceDeletionPolicy

  CityDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./city-data-function
      FunctionName: 'city-data-function'
      Description: 'City Data function used for internal services only.'
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      LoggingConfig:
        LogGroup: !Ref CityDataFunctionLogGroup
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CitiesTable
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: !Ref SpringProfile
    Metadata:
      BuildMethod: makefile

  CityDataFunctionLogAnomalyDetector:
    Type: AWS::Logs::LogAnomalyDetector
    Properties:
      LogGroupArnList:
        - !GetAtt CityDataFunctionLogGroup.Arn
      EvaluationFrequency: !Ref AnomalyDetectorEvaluationFrequency
      AnomalyVisibilityTime: 21 # days

Outputs:
  CitiesTableArn:
    Description: "Cities DynamoDB table ARN."
    Value: !GetAtt CitiesTable.Arn

  CityDataFunctionArn:
    Description: "City Data function ARN."
    Value: !GetAtt CityDataFunction.Arn
