name: "hiperium-cities"
services:
  
  city-read-function:
    image: "hiperium/city-read-function:1.0.0"
    container_name: "read-function"
    build:
      context: functions/city-read-function
      dockerfile: tools/docker/Dockerfile
    ports:
      - "9000:8080"
    environment:
      - AWS_LAMBDA_FUNCTION_NAME=city-read-function
    env_file:
      - utils/docker/lambda.env
    networks:
      - "cities-network"

  cities-localstack:
    image: "localstack/localstack:latest"
    container_name: "localstack"
    ports:
      - "4566:4566"
    env_file:
      - utils/docker/localstack.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./functions/city-read-function/src/test/resources/localstack/table-data.json:/var/lib/localstack/table-data.json
      - ./functions/city-read-function/src/test/resources/localstack/table-setup.sh:/etc/localstack/init/ready.d/1_table-setup.sh
    networks:
      - "cities-network"
    depends_on:
      - "city-read-function"

networks:
  cities-network:
