name: "spring-cd"
services:

  localstack:
    image: "localstack/localstack:latest"
    container_name: "spring-cd-localstack"
    ports:
      - "4566:4566"
    env_file:
      - spring.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../src/test/resources/localstack/table-data.json:/var/lib/localstack/table-data.json
      - ../../src/test/resources/localstack/table-setup.sh:/etc/localstack/init/ready.d/table-setup.sh
    networks:
      - "spring-cd-network"

networks:
  spring-cd-network:
