#####################################################################################
############################# Stage 1: Builder Image ################################
#####################################################################################
FROM hiperium/city-builder:latest as builder
WORKDIR /workspace

COPY pom.xml pom.xml
RUN  mvn dependency:go-offline -B
COPY src     src

RUN mvn -T 4C clean package -DskipTests -Ddependency-check.skip=true    && \
    mkdir -p target/extracted                                           && \
    unzip target/java-assembly.zip -d target/extracted)

#####################################################################################
############################ Stage 2: Application Image #############################
#####################################################################################
FROM hiperium/city-lambda:latest

COPY --from=builder /workspace/target/extracted ${LAMBDA_TASK_ROOT}

ENV AGENT_OUTPUT_DIR="/tmp/native-image-configs"
ENV MAIN_CLASS="hiperium.city.read.function.FunctionApplication"

RUN mkdir -p ${AGENT_OUTPUT_DIR}

ENTRYPOINT [ "${LAMBDA_TASK_ROOT}/bootstrap" ]
