#####################################################################################
############################# Stage 1: Builder Image ################################
#####################################################################################
FROM hiperium/city-builder:latest as builder
WORKDIR /workspace

COPY pom.xml    pom.xml
RUN  mvn dependency:go-offline -B
COPY src        src

RUN mvn -T 4C clean package -DskipTests -Ddependency-check.skip=true

#####################################################################################
############################ Stage 2: Application Image #############################
#####################################################################################
FROM public.ecr.aws/lambda/java:21-arm64

COPY --from=builder /workspace/target/city-read-function-aws.jar ${LAMBDA_TASK_ROOT}

CMD [ "org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest" ]
