#####################################################################################
############################# Stage 1: Builder Image ################################
#####################################################################################
FROM hiperium/city-builder:latest AS builder
WORKDIR /workspace

COPY pom.xml        pom.xml
RUN  mvn dependency:go-offline -B
COPY src            src
COPY tools/shell    tools/shell
COPY tools/assembly tools/assembly

RUN mvn -T 4C clean native:compile -Pnative -DskipTests -Ddependency-check.skip=true  && \
    mkdir -p target/extracted                                                         && \
    unzip target/native-assembly.zip -d target/extracted

#####################################################################################
############################ Stage 2: Application Image #############################
#####################################################################################
FROM public.ecr.aws/lambda/provided:al2023-arm64

COPY --from=builder /workspace/target/extracted ${LAMBDA_TASK_ROOT}

EXPOSE 8080
CMD [ "org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest" ]
