#####################################################################################
############################# Stage 1: Builder Image ################################
#####################################################################################
FROM hiperium/native-image-builder:latest AS builder
WORKDIR /workspace

COPY pom.xml        pom.xml
RUN  mvn dependency:go-offline -B
COPY src            src
COPY tools/shell    tools/shell
COPY tools/assembly tools/assembly

RUN mvn -T 4C clean native:compile -Pnative -DskipTests -Ddependency-check.skip=true

#####################################################################################
############################ Stage 2: Application Image #############################
#####################################################################################
FROM public.ecr.aws/lambda/provided:al2023-arm64
ARG APP_ROOT=/workspace

COPY --from=builder ${APP_ROOT}/target/native               ${LAMBDA_TASK_ROOT}
COPY --from=builder ${APP_ROOT}/tools/shell/bootstrap       ${LAMBDA_RUNTIME_DIR}
COPY --from=builder ${APP_ROOT}/target/native-assembly.zip  /var/tmp/data-function-assembly.zip

### Required to invoke the function correctly.
RUN chmod +x ${LAMBDA_RUNTIME_DIR}/bootstrap

EXPOSE 8080
CMD [ "org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest" ]
