#!/bin/sh

cd "${LAMBDA_TASK_ROOT:-.}" || {
    echo "cd command failed. Exiting."; exit 1;
}

java -agentlib:native-image-agent=config-output-dir="$AGENT_OUTPUT_DIR"  \
     -cp .:"$(echo lib/*.jar | tr ' ' :)"                                \
     "$MAIN_CLASS"
